/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBank,
  IBankInterface,
} from "../../../attacks/reentrancy.sol/IBank";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBank__factory {
  static readonly abi = _abi;
  static createInterface(): IBankInterface {
    return new Interface(_abi) as IBankInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBank {
    return new Contract(address, _abi, runner) as unknown as IBank;
  }
}
