/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  VulnerableBank,
  VulnerableBankInterface,
} from "../../uploaded/VulnerableBank";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Deposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Withdrawn",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getBankBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102fe8061001f6000396000f3fe60806040526004361061003f5760003560e01c806327e235e3146100445780633ccfd60b146100835780637b83b50b1461009a578063d0e30db0146100ad575b600080fd5b34801561005057600080fd5b5061007161005f366004610271565b60006020819052908152604090205481565b60405190815260200160405180910390f35b34801561008f57600080fd5b506100986100b5565b005b3480156100a657600080fd5b5047610071565b6100986101d6565b33600090815260208190526040902054806101045760405162461bcd60e51b815260206004820152600a6024820152694e6f2062616c616e636560b01b60448201526064015b60405180910390fd5b604051600090339083908381818185875af1925050503d8060008114610146576040519150601f19603f3d011682016040523d82523d6000602084013e61014b565b606091505b505090508061018e5760405162461bcd60e51b815260206004820152600f60248201526e151c985b9cd9995c8819985a5b1959608a1b60448201526064016100fb565b336000818152602081815260408083209290925590518481527f7084f5476618d8e60b11ef0d7d3f06914655adb8793e28ff7f018d4c76d505d5910160405180910390a25050565b600034116102165760405162461bcd60e51b815260206004820152600d60248201526c09aeae6e840e6cadcc8408aa89609b1b60448201526064016100fb565b33600090815260208190526040812080543492906102359084906102a1565b909155505060405134815233907f2da466a7b24304f47e87fa2e1e5a81b9831ce54fec19055ce277ca2f39ba42c49060200160405180910390a2565b60006020828403121561028357600080fd5b81356001600160a01b038116811461029a57600080fd5b9392505050565b808201808211156102c257634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220cf5108bed72438ede58174be4ead4c14b108c70d2d54b9344efadf366b0236f964736f6c634300081e0033";

type VulnerableBankConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VulnerableBankConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class VulnerableBank__factory extends ContractFactory {
  constructor(...args: VulnerableBankConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      VulnerableBank & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): VulnerableBank__factory {
    return super.connect(runner) as VulnerableBank__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VulnerableBankInterface {
    return new Interface(_abi) as VulnerableBankInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VulnerableBank {
    return new Contract(address, _abi, runner) as unknown as VulnerableBank;
  }
}
