/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ReentrancyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attackInProgress"
      | "getBalance"
      | "maxReentries"
      | "reentryCount"
      | "setMaxReentries"
      | "simulateAttack"
      | "target"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AttackFinished" | "AttackStarted" | "Reentered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attackInProgress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxReentries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reentryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxReentries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "simulateAttack",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "target", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "attackInProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxReentries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxReentries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simulateAttack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "target", data: BytesLike): Result;
}

export namespace AttackFinishedEvent {
  export type InputTuple = [finalBalance: BigNumberish];
  export type OutputTuple = [finalBalance: bigint];
  export interface OutputObject {
    finalBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttackStartedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReenteredEvent {
  export type InputTuple = [count: BigNumberish, contractBalance: BigNumberish];
  export type OutputTuple = [count: bigint, contractBalance: bigint];
  export interface OutputObject {
    count: bigint;
    contractBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Reentrancy extends BaseContract {
  connect(runner?: ContractRunner | null): Reentrancy;
  waitForDeployment(): Promise<this>;

  interface: ReentrancyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attackInProgress: TypedContractMethod<[], [boolean], "view">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  maxReentries: TypedContractMethod<[], [bigint], "view">;

  reentryCount: TypedContractMethod<[], [bigint], "view">;

  setMaxReentries: TypedContractMethod<
    [_max: BigNumberish],
    [void],
    "nonpayable"
  >;

  simulateAttack: TypedContractMethod<[], [void], "payable">;

  target: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attackInProgress"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxReentries"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reentryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMaxReentries"
  ): TypedContractMethod<[_max: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "simulateAttack"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "target"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AttackFinished"
  ): TypedContractEvent<
    AttackFinishedEvent.InputTuple,
    AttackFinishedEvent.OutputTuple,
    AttackFinishedEvent.OutputObject
  >;
  getEvent(
    key: "AttackStarted"
  ): TypedContractEvent<
    AttackStartedEvent.InputTuple,
    AttackStartedEvent.OutputTuple,
    AttackStartedEvent.OutputObject
  >;
  getEvent(
    key: "Reentered"
  ): TypedContractEvent<
    ReenteredEvent.InputTuple,
    ReenteredEvent.OutputTuple,
    ReenteredEvent.OutputObject
  >;

  filters: {
    "AttackFinished(uint256)": TypedContractEvent<
      AttackFinishedEvent.InputTuple,
      AttackFinishedEvent.OutputTuple,
      AttackFinishedEvent.OutputObject
    >;
    AttackFinished: TypedContractEvent<
      AttackFinishedEvent.InputTuple,
      AttackFinishedEvent.OutputTuple,
      AttackFinishedEvent.OutputObject
    >;

    "AttackStarted(uint256)": TypedContractEvent<
      AttackStartedEvent.InputTuple,
      AttackStartedEvent.OutputTuple,
      AttackStartedEvent.OutputObject
    >;
    AttackStarted: TypedContractEvent<
      AttackStartedEvent.InputTuple,
      AttackStartedEvent.OutputTuple,
      AttackStartedEvent.OutputObject
    >;

    "Reentered(uint256,uint256)": TypedContractEvent<
      ReenteredEvent.InputTuple,
      ReenteredEvent.OutputTuple,
      ReenteredEvent.OutputObject
    >;
    Reentered: TypedContractEvent<
      ReenteredEvent.InputTuple,
      ReenteredEvent.OutputTuple,
      ReenteredEvent.OutputObject
    >;
  };
}
